### ISSUE TITLE
Add "Reason for change" to client, case, charge, and status change

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/cmr-clinic-admin-api#15]
- [X] Determine if we should use one table of changes for all three tables `clients`, `convictions`, and `charges`.
    Will be one table
- [X] Create the table(s) . See Create histories #26
- [ ] Add to edit screens
-

**Comment by mattsplat** [comment]
@zmon See if this is done

**Comment by zmon** [comment]
Status is a part of applicant.
