### ISSUE TITLE
Create Statute Lookup

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/cmr-clinic-admin-api#18]
Currently, we have two Word documents that contain a list of statues that are eligible and non-elegiable. These documents are in the `doc` directory of this repository

* LIST OF CRIMES ELIGIBLE FOR EXPUNGEMENT.docx
* LIST OF CRIMES not eligible for expungement.docx

The first step is to look at the documents and suggest how they should be stored (what fields and tables)

* statute number - text . 9999.9999
* statute name - text
* eligible Y/N/Null/Possible
* note textarea

**COMMENTS** There may be a need to have a comments table on this.

* user_id creating the comment
* comment - text field
* Will have the normal time stamps and who added, edit, and deleted
* soft deletes

**HISTORY** this may be another table that we want its own history for.

The second step is to load these into a table and generate a CRUD to update them.

The third step is to create a combo box that would allow users of the applicant edit screens to:

1. Select from an existing entry
2. Add an entry - if one was missing

The fourth step, integrate into the current applicant screen

**Comment by mattsplat** [comment]
Still needed 

1.  add the select vue component to add or select statute
2. add name(subject) column to comments

**Comment by mattsplat** [comment]
done
