### ISSUE TITLE
Implement Cancel action on Applicant, Case, and Charges

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/cmr-clinic-admin-api#35]
The button and function exist.

Start with charges since it has saved the initial values.

If you have a better way than below please implement it.

1. When mounted save the original values.
2. On cancel, restore original values
3. Return to detail display

**Comment by mattsplat** [comment]
@zmon  Can you check if there is anything left to do here?

**Comment by zmon** [comment]
@mattsplat 

Case it works on all fields except for Release Date where the flat picker is used.
Charges it works on all input fields, but does not work on any of the SELECTs
The Cancel is still not working on Applicant.

This is how I created my test site
```
rm -rf pull
git clone git@github.com:codeforkansascity/cmr-clinic-admin-api.git pull
cd pull
cp ../env .env
git fetch origin feature/vue-version
git checkout feature/vue-version
rm -fr package-lock.json composer.lock vendor node_modules
composer install
npm install
npm run dev
```
